### ISSUE TITLE
Question about account creation

### ISSUE THREAD

**Issue by aaahrens** [sagemathinc/cocalc-docker#10]
Hi devs,

So I'm running my own remote installation of cocalc, and I can create users through the database.

However, I am having issues with having users make their own accounts (through the standard sign up window). Is there documentation regarding the user registration process or is this a bug?

Also, to provide context, the load server info and hub connector are both perpetually connecting.

**Comment by haraldschilly** [comment]
Hello, do you run the docker image or not? We generally do not give support, though.

But at least to make this clear, without being connected you cannot do anything including signing up.

**Comment by drunkengranite** [comment]
So the issue is proxy passing with nginx. When I run it touching the machines 443 port it works fine, but proxying through nginx makes it not able to connect.

**Comment by williamstein** [comment]
Not an issue...
