### ISSUE TITLE
Support for ARM

### ISSUE THREAD

**Issue by kevin2107** [sagemathinc/cocalc-docker#100]
With new compute capabilities from amazon, R6g instances are their cheaper alternative to their instances made for memory and compute intensive workloads. R6g instances can only be ran using the ARM architecture.

**Comment by williamstein** [comment]
This is also now very relevant to Apple's M1 chip, since with the latest cocalc-docker x86_64 running via Rosetta2, we have:
```sh
~$ sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 9.3, Release Date: 2021-05-09                     │
│ Using Python 3.8.5. Type "help()" for help.                        │
└────────────────────────────────────────────────────────────────────┘
cysignals sigaltstack: Invalid argument
```

So I should build cocalc-docker for both architectures.

**Comment by williamstein** [comment]
There is now an official image: https://hub.docker.com/r/sagemathinc/cocalc-aarch64
