### ISSUE TITLE
using ssh tunnel on ipad never got connected

### ISSUE THREAD

**Issue by benhaotang** [sagemathinc/cocalc-docker#102]
![IMG_0536](https://user-images.githubusercontent.com/50174724/93412448-c679a100-f8cf-11ea-8721-399011e5fcc6.jpeg)

my open cocalc works on ipad through nginx reverse porting, but I found it to be insecure, but when I turn to ssh tunnel, it never got connected, what should I do?

**Comment by williamstein** [comment]
I don't understand the question, and it's a year later so I'm guessing it's stale.
