### ISSUE TITLE
How to setup a system wide proxy configuration for all users ?

### ISSUE THREAD

**Issue by mperreir** [sagemathinc/cocalc-docker#105]
Hello,

I'm trying to get all my users fetch our proxy config automatically so that they can for example "git pull" without additional configuration.
I've tried adding some line in /etc/environnement or adding  /etc/profile.d/proxy configuration file in the docker container but it does not get propagated to cocalc users (even if it works when I directly log into the docker container).

/etc/skel could be a solution for new users (modifying the template for .bashrc for example) but it would not do anything for existing users :-(

Has any of you already faced that problem ?

**Comment by williamstein** [comment]
This seems like a general Linux question.

**Comment by mperreir** [comment]
Well not really because what works on a usual Linux OS (outside of the Cocalc docker container) does not in the container :-).

**Comment by williamstein** [comment]
OK, re-opening!
