### ISSUE TITLE
problem with cypari.h

### ISSUE THREAD

**Issue by orkolorko** [sagemathinc/cocalc-docker#11]
In the last version of the docker image,
when using load() it seems like cython
has an issue.

It cannot compile because it cannot find "cypari.h".

The following foo.spyx shows the issue

```
cimport sage.rings.real_mpfi   
from sage.rings.real_mpfr cimport RealNumber, RealField_class
from sage.rings.real_mpfi cimport RealIntervalFieldElement, RealIntervalField_class

from cpython cimport bool

cdef float test_sum(float x, float y):
    return x+y
```

**Comment by williamstein** [comment]
This seems like a general Sage problem or question, right?
