### ISSUE TITLE
Cannot apply licenses

### ISSUE THREAD

**Issue by ingodahn** [sagemathinc/cocalc-docker#113]
I have an installation of CoCalc from Dockerhub where I have CoCalc admin rights. As admin I can define licenses and assign them to email adresses as license manager.

But I don't see how users can apply these licenses as they neither see a license tab in their account page nor an "Upgrade contribution..." button in their project setting pages.
I don't want to sell licenses but use them only to control usage of the test server resources.

**Comment by williamstein** [comment]
I can confirm that use of licenses is not yet implemented for cocalc-docker.  The only thing they would impact is the idle timeout and always running, since cocalc-docker has no support at all for any other quotas *yet*.

**Comment by williamstein** [comment]
The answer now is to go to the admin settings page and enable the commercial UI functionality.  This is implemented and can be very useful.
