### ISSUE TITLE
Projects appear offline after docker build

### ISSUE THREAD

**Issue by fsp-c** [sagemathinc/cocalc-docker#117]
Due to some specific needs, I have attempted to install texlive-full through the Dockerfile instead of the basic texlive. I have now tried to build the docker image from this repo about 10 times or more. Each time I have built it, it has completed, but when accessing the localhost page and creating my account, any project, new or old appears offline, even though the "project starting" message is gone. 

After all the attempts to include texlive-full, I decided to try and build the project as is, with no modifications, right after I had cloned the repo, to see if it was my modifications causing the issues. But it turned out that my problem persisted. 

This is how all projects are stuck after starting or creating them:
![Screenshot 2021-05-20 at 10 23 24](https://user-images.githubusercontent.com/84209641/118945171-7f0f4d00-b955-11eb-917a-848655133729.png)

I can't access the table of processes either as it tells me to restart the project, to no avail:
![Screenshot 2021-05-20 at 10 26 47](https://user-images.githubusercontent.com/84209641/118946777-0610f500-b957-11eb-9c46-adfed68d0fd4.png)

Under the "New" tab, when trying to create a new file, clicking on any of the file types doesn't do anything:
![Screenshot 2021-05-20 at 10 53 04](https://user-images.githubusercontent.com/84209641/118949597-b08a1780-b959-11eb-8c4c-773642cfb919.png)

As a side note, the project works flawlessly when running it from the sagemathinc/cocalc dockerhub image. I just can't get it to work when building the image myself.

I hope someone can help with this problem as this project is exactly what I needed. Also, if more info is needed I will happily try my best to provide it!

**Comment by williamstein** [comment]
Things are in a significant state of flux regarding building cocalc-docker from source right now.  I hope it will stabilize within the next week.

In the meantime, you could just take our officially published image -- which works for you, right -- and do one of the following two things:

1. Extend it via your own Dockerfile.  Dockerfiles often start with e.g., `FROM ubuntu:20.04`, but you can put anything there for the image you want to start with.  Just replace `ubuntu:20.04` by cocalc's...
2. Alternatively, take the standard image, then do `sudo docker exec -it cocalc /bin/bash` and then `apt update; apt install ...` right there.

**Comment by fsp-c** [comment]
Hi William,
Thanks for getting back to me so quickly!

1. Thats an interesting idea! I never really thought of that as I am not overly experienced with docker yet.
2. Yeah, that was initially my backup plan as well.

I'm looking forward to following the development, and the potential stability in the future as you mentioned. 
Really appreciate all the work that must have gone into this project as it is really a perfect solution for my use case! Thanks!

**Comment by williamstein** [comment]
> I'm looking forward to following the development, and the potential stability in the future as you mentioned.

I'm revamping the cocalc part of the installation to just involve installing some pre-pbuilt packages from npmjs like this one https://www.npmjs.com/package/smc-hub

That will make the installation (and also development) process with cocalc-docker much more stable, rather than building smc-hub (and all the other part of cocalc) from source directly as part of the docker build.

**Comment by fsp-c** [comment]
> That will make the installation (and also development) process with cocalc-docker much more stable, rather than building smc-hub (and all the other part of cocalc) from source directly as part of the docker build.

That sounds really promising for future customisation of docker images as well, as I suppose it will make it easier to differentiate between necessary parts of the application "engine room" and parts of the features that could be excluded or expanded upon for a specific use case? 
In my case, I guess I could potentially save some image space and build time, as I am not currently using all of the features in the image.
