### ISSUE TITLE
Dockerfile install.py doesn't match current cocalc repository

### ISSUE THREAD

**Issue by paqui003** [sagemathinc/cocalc-docker#120]
Good day, 

I was trying to build an updated Docker image by using cloning this repo and using
> docker build -t cocalc .   

In the Dockerfile a git clone from your cocalc repository is executed first and after that, you run _install.py_. However install.py is no longer stored in _cocalc/src_ (master branch). There seems to be a missmatch between the Dockerfile commands and your cocalc repository. 

Do we still need to executed install.py?

Thank you very much for your help in advance. 

- Paqui004

**Comment by williamstein** [comment]
It's not possible to build/use cocalc-docker from source using the latest master right now.  If you need to do so, you'll have to use a commit from about 2 weeks ago, both for cocalc-docker and cocalc, or wait a week or so.

**Comment by paqui003** [comment]
Thank you for your reply.
