### ISSUE TITLE
Bug: [Out] not showing in Cocalc Notebook Cells

### ISSUE THREAD

**Issue by mafloh** [sagemathinc/cocalc-docker#128]
## Bug Description
Cells process (showing a small arrow pointing to the left) but do not show [Out] with output, nor an error. It is a fresh install with Ubuntu 20.04 and nginx reverse proxy.

A few times it has worked, I could not reproduce. Sometimes the backend is spawning forever, sometimes it is ready. Same behaviour in both cases.

Classic Jupyter Notebook works like a charm.

## Troubleshooting
- Switching Python Kernels, reloading the page, restarting the processes did not help. 
- The processes page show red Memory, however the server uses only a few hundred MB of 4 GB Ram. Disk Space is plenty too.
- **Logs:** `/var/log/hub.log` and `~/.smc/logs/log`do not exist (?)

I can send the server address in a private message.

**Comment by williamstein** [comment]
- Yes, I can reproduce this with the latest version.   This is very weird, given that the exact same code is running in numerous other environments well.  Very, very weird.   I've never seen this sort of bug before.  Will fix it asap.

- The logs are in /var/log/hub for the systemwide hub and ~/.smc/logs/log for each project.  They are there.

**Comment by williamstein** [comment]
I've fixed https://github.com/sagemathinc/cocalc/issues/5467 and I really don't have any other ideas related to even reproducing this... so I'm closing it.   If you do update to the new version of cocald-docker (from right now) and test this, let me know if it works.

**Comment by mafloh** [comment]
I confirm the issue is solved. Thanks so much!
