### ISSUE TITLE
Delete operations timeout

### ISSUE THREAD

**Issue by kebesing** [sagemathinc/cocalc-docker#131]
When I attempt to delete files inside of a project, I get an error that says that the operation has timed out.

**Comment by kebesing** [comment]
The issue appears to be with deleting, renaming, or moving files. The first time one of these commands is given to a file the operation fails due to a timeout error. If you repeat the command (in the case of renaming, it doesn't need to be the same rename command), the operation is completed immediately. I'm relatively new to docker, so I'm open to the idea that this could be a configuration issue on that end. However, I have been running this CoCalc instance for several years and don't recall this behavior in the past.

**Comment by belonesox** [comment]
`However, I have been running this CoCalc instance for several years and don't recall this behavior in the past.`

To many possible causes — 
* your VM could be overloaded
* your server with VM can be overloaded
* something wrong with docker filemapping (earlier versions of docker has lot of file IO-issues)
* …

Probably, you should
* report your OS (``cat /etc/*ele*``) and version of docker/podman. 
* try open term inside docker container and make some FIO tests again mapped folder.
** for example 
```
touch /projects/testfio
time shred -s1G  /projects/testfio
```
and same test should be repeated outside container, on host VM.

(for example, I on relatively bad VM and HDD have «real 4m21s» inside container and  «́≈4m24s» outside).
