### ISSUE TITLE
How can I pass my own postgresql database

### ISSUE THREAD

**Issue by NeilJ12** [sagemathinc/cocalc-docker#132]
Hi, I hope you are doing well
I want to use my own postgresql database to run your image but it doesn't work.
That's my command :  
```
docker run -e PGHOST=${host} -e PGUSER=${username} --name=cocalc -d -v ~/cocalc:/projects -p 443:443 sagemathinc/cocalc
```

I'm on Mac OS

**Comment by williamstein** [comment]
See https://github.com/sagemathinc/cocalc-docker/blob/master/docs/external-postgresql.md
