### ISSUE TITLE
Cannot install CoCalc on Ubuntu - Cannot find gdb installed

### ISSUE THREAD

**Issue by ingodahn** [sagemathinc/cocalc-docker#133]
When installing Cocalc-Docker on Ubuntu 20, launching a notebook with Sage Kernel gives the following error:

![image](https://user-images.githubusercontent.com/3258024/134399993-10461fd6-2d6b-43c0-b213-6d003f79d300.png)

That makes the system unusable.

This happens with a fresh Ubuntu VM in Virtual box on a Win 10 PC as well as on a fresh Ubuntu installation in the cloud.

**Comment by williamstein** [comment]
I upgraded us to sage-9.4 and people reported some issues like this, so I downgraded to sage-9.3, and there were additional issues.  The sage devs say this is a problem introduced in sage-9.3 that's not present in sage-9.2, so I downgraded cocalc-docker to the old sage-9.2 and built a new image, which is what is live now (which you should confirm you're using), and the people who had reported issues with illegal instructions so far said that they were solved.   If you're using the latest cocalc-docker and it has sage-9.2 in it (which should be the case), then there is nothing more I can do to help with your problem, except to recommend that you build or re-build sage from source on the machine where you have this problem.

**Comment by ingodahn** [comment]
I did the following in an Ubuntu 20 VM:
* Removed all docker containers
* Re-installed docker-cocalc from Github (I don't know where to find the info on the sage version)
* Opened the notebook I created in the previously installed version and the error re-appeared
* Deleted that notebook
* Created a new notebook and it worked
* Imported a notebook and it worked.
Thus, the current version is working as expected and I close this issue.
