### ISSUE TITLE
update to latest version

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc-docker#14]
Right now this doesn't work too well, though the last binary I posted does work.

1. Building works.

2. The kernel for jupyter defaults to anaconda3, but the docker image doesn't have anaconda3 at all.  Fix -- change kernel default to Sage, or install anaconda3.  I think the later makes sense.

3. The Jupyter kernel for sage (v 8.1) itself doesn't work at all (though sage worksheets work fine).  The problem is:
```
~$ jupyter console --kernel=sagemath
Traceback (most recent call last):
  File "/usr/local/sage/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/sage/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/sage/local/lib/python2.7/site-packages/sage/repl/ipython_kernel/__main__.py", line 1, in <module>
    from ipykernel.kernelapp import IPKernelApp
  File "/usr/local/sage/local/lib/python2.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/usr/local/sage/local/lib/python2.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/usr/local/sage/local/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/usr/local/sage/local/lib/python2.7/site-packages/IPython/core/application.py", line 16, in <module>
    from copy import deepcopy
  File "/usr/local/sage/local/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/sage/local/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```

**Comment by embray** [comment]
Looks to be related to this Debian bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=852163  I'm not satisfied with the suggested workaround of "don't install Python in `/usr/local`" since obviously that should work without being completely broken.  I'm not sure if the bug here is in Python (I'm guessing not since it also seems to impact Python 2.7, though it could still be a backported regression), or (more likely) a bug in Debian/Ubuntu's Python packages...

**Comment by embray** [comment]
FWIW the Docker images for Sage install all Sage-related stuff in `/opt/sage` .

**Comment by embray** [comment]
(Though it's still weird that even `/usr/local/sage` would be a problem...)

**Comment by embray** [comment]
Ah, I see now. More details here: https://bugs.launchpad.net/ubuntu/+source/python3.5/+bug/1682934

**Comment by DrXyzzy** [comment]
Here is a difference between .sagews in this image and in production cocalc, where Docker is better. If I execute a cell and then highlight text in the output in production CoCalc, the highlighting disappears after a few seconds. If I do the same in the docker image, the text stays highlighted. I'm doing tests for production and Docker CoCalc in Chrome browser.

![highlighting-sagews](https://user-images.githubusercontent.com/528072/33993551-a5ac772a-e09c-11e7-95e6-3e0c00a255c5.png)

**Comment by DrXyzzy** [comment]
might be nice to add bash kernel, if only to support %sh mode in sagews

**Comment by williamstein** [comment]
Thanks @embray, I would have not guessed this was the problem!   -- I'll try building/installing sage in /opt, since there's probably no need to put it in /usr/local.

**Comment by williamstein** [comment]
Our current kernel.json files for sage are the ancient horrible ones from before and now don't work (with the opt change).   See https://github.com/sagemathinc/cocalc/wiki/CustomerJupyterKernel for help.

Also, I'm finding that the terminal is a disaster again --- constantly resetting/reconnecting and control/resize codes.  

Upgrading the docker image will be a lot of work.

**Comment by embray** [comment]
I don't fully understand the issues here but I'll see if I can find some time to help out.
