### ISSUE TITLE
Install Nix package manager

### ISSUE THREAD

**Issue by sheepforce** [sagemathinc/cocalc-docker#140]
It would be great if the Docker image would come with a multi user installation the Nix package manager and language. (https://nixos.org/manual/nix/stable/installation/installing-binary.html#multi-user-installation).

It would give access to the large nix package collection to all projects and enables creation of reproducible software environments, making access to additional dependencies, that are missing in the Ubuntu docker container, easy. Unfortunately this cannot be done conveniently as a user, but requires a setup of the daemon with super user permissions once.

**Comment by williamstein** [comment]
Are you manually installing this for your deployment right now?

**Comment by sheepforce** [comment]
I would like to but it is not as easy in the docker container, as it is on a normal Ubuntu. The Nix installer expects not to be run as root. The [official Nix docker container builds around Alpine](https://github.com/NixOS/docker/blob/master/Dockerfile) and the Dockerfile does most of the work the installer would normally do. There is also a Nix installation in the Ubuntu Docker container [here](https://github.com/OdysLam/ddapptools/blob/main/docker/Dockerfile), but it also failed and I was a little bit lost with all the stuff going on in the CoCalc container :slightly_smiling_face: Otherwise I'de like to be of help where I can.

**Comment by williamstein** [comment]
Closing since this seems out of scope for this project.
