### ISSUE TITLE
restarting a project with a custom command

### ISSUE THREAD

**Issue by onayg** [sagemathinc/cocalc-docker#142]
I installed syncthing into the docker, configured so that it syncs a project with my computer. 
When I restart a project I restart accordingly syncthing from the terminal file. 

I would be nice to automatize this, e.g. running syncthing --no-browser at every restart.

What is the best way?

**Comment by williamstein** [comment]
In theory this is the best way -- https://doc.cocalc.com/project-init.html

I'm not 100% certain this is supported in cocalc-docker though.  Give it a try.

**Comment by williamstein** [comment]
https://doc.cocalc.com/project-init.html is definitely fully supported in cocalc-docker, and does solve this problem.
