### ISSUE TITLE
Base folder of distributed handout has root permissions

### ISSUE THREAD

**Issue by vdtoorn** [sagemathinc/cocalc-docker#146]
When a **nested** folder is distributed as a handout, the files are correctly moved form the 'course' project to the student's project, and the ownership of the contained folder is correctly set.

Unfortunately the lowest folder has 'root' as owner and can't be opened by the student. The course project assignment folder does not have the root owner.

**Comment by aaszodi** [comment]
I have seen the same behaviour when assigning homework.  I used the image with ID `63ee29abd54b`, which is not the most up-to-date version (I am currently in the process of `docker pull` -ing the latest image).
This is a serious bug because it makes teaching with the CoCalc Docker image impossible.

**Comment by aaszodi** [comment]
Tried it with the currently latest image, ID `de641cb0215a`. The problem still persists. If I assign a homework that lives in my teacher's project in `assignments/task`, then the leaf directory `task` will be correctly `chown`-ed to the student's ID. However, the `assignments` directory will be owned by `root` within the student's project, permissions `700`, making it inaccessible for the student. The fix should be to `chown -R` the whole copied hierarchy.

**Comment by aaszodi** [comment]
The saga continues: With the workaround described in my previous comment I can assign a homework, but I cannot collect it from the student, see attached screenshot. Permission handling must be fixed.

<img width="285" alt="Screen Shot 2021-12-28 at 11 34 18" src="https://user-images.githubusercontent.com/3216453/147557652-4d98a7f3-83b6-4800-b8c8-ae99cdbbddbd.png">

**Comment by williamstein** [comment]
This is now fixed in master, and will be in the next cocalc-docker image that I post to dockerhub (should be sometime today).

**Comment by williamstein** [comment]
Pushing new image now.

**Comment by aaszodi** [comment]
Many thanks! I can confirm that homework assignment/collection works as expected in the _Intel_ version of the CoCalc Docker container.
