### ISSUE TITLE
How to enable custom-enviroments / project?

### ISSUE THREAD

**Issue by arm2arm** [sagemathinc/cocalc-docker#150]
I was wondering if the https://doc.cocalc.com/software.html#custom-environments future is available to the docker image.

thank you beforehand.

**Comment by williamstein** [comment]
No, but you can do almost anything to customize cocalc-docker as explained here:  https://github.com/sagemathinc/cocalc-docker/blob/master/README.md#adding-custom-software-to-your-cocalc-instance

You could certainly accomplish anything that could be solved with  https://doc.cocalc.com/software.html#custom-environments  via that approach.
