### ISSUE TITLE
FATAL: database "smc" does not exist

### ISSUE THREAD

**Issue by YikeStone** [sagemathinc/cocalc-docker#156]
I am using the cocalc-aarch64 image. It is still giving this error. #116  This issue was closed but I am still getting it. It does not matter if I use a docker volume or external mounted volume. No matter how many times I stop it and restart. I dont have any knowledge about postgres nevertheless I tried to manually create a smc database from inside docker container unsuccessfully. I am begging could anyone pls help me with this? I am at my wits end here. I am on the verge of going bald.

'''
LOG: init_projects_path: initialize /projects path
LOG: self_signed_cert
LOG: ssl key and cert exist, so doing nothing further
LOG: root_ssh_keys: creating them
LOG: run rm -rf /root/.ssh/
rm -rf /root/.ssh/
LOG: run ssh-keygen -t ecdsa -N '' -f /root/.ssh/id_ecdsa
Generating public/private ecdsa key pair.
Created directory '/root/.ssh'.
Your identification has been saved in /root/.ssh/id_ecdsa
Your public key has been saved in /root/.ssh/id_ecdsa.pub
The key fingerprint is:
SHA256:qxcJcftoiYzjx++cLYj1J3DXEINY50/i+saccEZibVs root@a498ce5ece23
The key's randomart image is:
+---[ECDSA 256]---+
|       o...      |
|      o ooo      |
|       o ooo.    |
|      . +.=+E    |
|     o +SO.=.    |
|    o = Oo* .    |
|   . = *oO .     |
|    o +o=+*      |
|     ..+==o      |
+----[SHA256]-----+
ssh-keygen -t ecdsa -N '' -f /root/.ssh/id_ecdsa
LOG: run cp -v /root/.ssh/id_ecdsa.pub /root/.ssh/authorized_keys
'/root/.ssh/id_ecdsa.pub' -> '/root/.ssh/authorized_keys'
cp -v /root/.ssh/id_ecdsa.pub /root/.ssh/authorized_keys
LOG: start_ssh
LOG: starting ssh
LOG: run service ssh start
 * Starting OpenBSD Secure Shell server sshd
   ...done.
service ssh start
LOG: start_postgres
LOG: postgres_perms: ensuring postgres directory perms are sufficiently restrictive
LOG: run mkdir -p /projects/postgres && chown -R sage. /projects/postgres && chmod og-rwx -R /projects/postgres
mkdir -p /projects/postgres && chown -R sage. /projects/postgres && chmod og-rwx -R /projects/postgres
LOG: start_postgres: starting the server
LOG: start_hub
LOG: run pkill -f cocalc-hub-server
pkill -f cocalc-hub-server
LOG: run mkdir -p /var/log/hub && cd /cocalc/src/packages/hub && npm run hub-docker-prod > /var/log/hub/out 2>/var/log/hub/err &
mkdir -p /var/log/hub && cd /cocalc/src/packages/hub && npm run hub-docker-prod > /var/log/hub/out 2>/var/log/hub/err &
LOG: reset_project_state: ensuring all projects are set as opened (not running) in the database
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: could not connect to server: Connection refused
        Is the server running locally and accepting
        connections on Unix domain socket "/projects/postgres/data/socket/.s.PGSQL.5432"?
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: could not connect to server: Connection refused
        Is the server running locally and accepting
        connections on Unix domain socket "/projects/postgres/data/socket/.s.PGSQL.5432"?
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  the database system is starting up
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  database "smc" does not exist
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  database "smc" does not exist
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  database "smc" does not exist
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  database "smc" does not exist
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  database "smc" does not exist
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  database "smc" does not exist
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  database "smc" does not exist
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  database "smc" does not exist
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  database "smc" does not exist
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  database "smc" does not exist
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  database "smc" does not exist
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  database "smc" does not exist
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  database "smc" does not exist
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  database "smc" does not exist
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  database "smc" does not exist
echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
LOG: run echo "update projects set state='{\"state\":\"opened\"}';" | psql -t
psql: FATAL:  database "smc" does not exist

'''

**Comment by williamstein** [comment]
Just a note that I haven't updated cocalc-aarch64 in a while.  I tried this week using the latest Docker desktop on my M1 mac, but it actually fully crashed Docker itself.    I'll try again next week.  I also created a new lightweight version of cocalc-docker (see Dockerfille-lite), and could also try that, as it's much less likely to lead to a crash.

**Comment by edgarcosta** [comment]
I think the issue is that the command `npm run hub-docker-prod`
fails with `could not determine executable to run`, here is my debug output:
```
0 verbose cli /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@9.1.1
2 info using node@v16.18.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 3ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/cocalc/src/packages/hub/.npmrc Completed in 0ms
10 timing config:load:project Completed in 4ms
11 timing config:load:file:/root/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 15ms
17 timing npm:load:configload Completed in 15ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm exec cocalc-hub-server --mode=multi-user --all --hostname=0.0.0.0 --https-key=/projects/conf/cert/key.pem --https-cert=/projects/conf/cert/cert.pem
21 verbose argv "exec" "--" "cocalc-hub-server" "--mode=multi-user" "--all" "--hostname=0.0.0.0" "--https-key=/projects/conf/cert/key.pem" "--https-cert=/projects/conf/cert/cert.pem"
22 timing npm:load:setTitle Completed in 3ms
23 timing config:load:flatten Completed in 3ms
24 timing npm:load:display Completed in 4ms
25 verbose logfile logs-max:10 dir:/root/.npm/_logs/2022-11-12T21_44_31_265Z-
26 verbose logfile /root/.npm/_logs/2022-11-12T21_44_31_265Z-debug-0.log
27 timing npm:load:logFile Completed in 4ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 28ms
31 silly logfile done cleaning log files
32 timing config:load:flatten Completed in 1ms
33 timing arborist:ctor Completed in 2ms
34 verbose shrinkwrap failed to load node_modules/.package-lock.json missing from lockfile: node_modules/abab
35 timing command:exec Completed in 4852ms
36 verbose stack Error: could not determine executable to run
36 verbose stack     at getBinFromManifest (/usr/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
36 verbose stack     at exec (/usr/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:185:15)
36 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:133:5)
37 verbose pkgid @cocalc/hub@1.108.4
38 verbose cwd /cocalc/src/packages/hub
39 verbose Linux 5.15.49-linuxkit
40 verbose node v16.18.1
41 verbose npm  v9.1.1
42 error could not determine executable to run
43 verbose exit 1
44 timing npm Completed in 4896ms
45 verbose code 1
46 error A complete log of this run can be found in:
46 error     /root/.npm/_logs/2022-11-12T21_44_31_265Z-debug-0.log
```

**Comment by williamstein** [comment]
This seems out of date or no longer meaningful to me.
