### ISSUE TITLE
enable external database support

### ISSUE THREAD

**Issue by mzramna** [sagemathinc/cocalc-docker#160]
since so many people has problems with fresh install of cocalc because of the postgres database,it could be good to use an external docker database,using an user administrated database could also simplify to cases like a docker swarm and do less exposed filesystem,could be added using an pre defined docker-compose file or just give an how to create your own database,and since the cocalc itself already can install the database and populate it,probly will be an easy step to this,i'm half way to the standalone database,only missing to find the user and password needed to cocalc identify the standalone database already existing in docker
i simply created a env called `PGHOST` with the database address,the database detects that i'm trying to connect,but the password provided by the cocalc cannot match to mine database password,wich btw is empty

**Comment by mzramna** [comment]
references: #132 #116 #134

**Comment by williamstein** [comment]
Using an external postgresql is now fully supported. See https://github.com/sagemathinc/cocalc-docker/blob/master/docs/external-postgresql.md

This work was funded by https://www.yields.io/, so thanks to them!
