### ISSUE TITLE
cocalc crashes when tying to open Registration Tokens menu in Site Administration

### ISSUE THREAD

**Issue by szazs89** [sagemathinc/cocalc-docker#179]
I have recently upgraded my docker image to version 20.10.12 (the previous one was used since more than a year, I am not sure about the exact version number).
Now, when I try to set up registration tokens as admin cocalc crashes with the following message:
<details><summary>Application Error: TypeError: e.fromNow is not a function @ 1/63168 of https://cocalc.mm.bme.hu/static/cc6b44cb5caa3bb90f40.js</summary>

```
render@https://cocalc.mm.bme.hu/static/cc6b44cb5caa3bb90f40.js:1:63168
45582/P/ee<@https://cocalc.mm.bme.hu/static/30a91e947766980d3f61.js:1:41319
o@https://cocalc.mm.bme.hu/static/app-2eba4b903149260c6dd5.js?9a36924477bcb75e903e:2:5044892
45582/P/ee<@https://cocalc.mm.bme.hu/static/30a91e947766980d3f61.js:1:41197
P@https://cocalc.mm.bme.hu/static/30a91e947766980d3f61.js:1:41596
xo@https://cocalc.mm.bme.hu/static/load-21cba8b3d021e517895e.js?9a36924477bcb75e903e:2:74043
Pi@https://cocalc.mm.bme.hu/static/load-21cba8b3d021e517895e.js?9a36924477bcb75e903e:2:85664
xi@https://cocalc.mm.bme.hu/static/load-21cba8b3d021e517895e.js?9a36924477bcb75e903e:2:84872
Ei@https://cocalc.mm.bme.hu/static/load-21cba8b3d021e517895e.js?9a36924477bcb75e903e:2:84477
Eu@https://cocalc.mm.bme.hu/static/load-21cba8b3d021e517895e.js?9a36924477bcb75e903e:2:134347
_c@https://cocalc.mm.bme.hu/static/load-21cba8b3d021e517895e.js?9a36924477bcb75e903e:2:119988
vc@https://cocalc.mm.bme.hu/static/load-21cba8b3d021e517895e.js?9a36924477bcb75e903e:2:119916
gc@https://cocalc.mm.bme.hu/static/load-21cba8b3d021e517895e.js?9a36924477bcb75e903e:2:119777
oc@https://cocalc.mm.bme.hu/static/load-21cba8b3d021e517895e.js?9a36924477bcb75e903e:2:116584
lc@https://cocalc.mm.bme.hu/static/load-21cba8b3d021e517895e.js?9a36924477bcb75e903e:2:115139
k@https://cocalc.mm.bme.hu/static/load-21cba8b3d021e517895e.js?9a36924477bcb75e903e:2:164277
L@https://cocalc.mm.bme.hu/static/load-21cba8b3d021e517895e.js?9a36924477bcb75e903e:2:164808
```
</details>

Maybe it is about the earlier created tokens, and deleting them would help, but I do not know how can I manage them (list, delete, etc.) through the API.

Other thing that came into my mind to downgrade, i.e. to pull some older docker image, but I am not sure about how problematic it can be.

**Comment by williamstein** [comment]
Pushing images now.  You can verify that they are live at https://hub.docker.com/u/sagemathinc

**Comment by szazs89** [comment]
it's fine! Thanks. (The behaviour of the Add button is a bit weird: it opened the existing token and then it took me a time to figure out that by pressing Reset create a new token without deleting the old one... I guess)

**Comment by williamstein** [comment]
> The behaviour of the Add button is a bit weird

I agree.  @haraldschilly your "Add Registration token" UI is a bit funny due to not reseting state properly when used more than once.  Maybe look into it -- I bet you can easily improve it.
