### ISSUE TITLE
Cannot download shared files

### ISSUE THREAD

**Issue by Maarrk** [sagemathinc/cocalc-docker#185]
On the public page of a shared file, after clicking the links "Embed", "Download" and "Raw", the page shown is "404 - Page Not Found". The "Edit" button works as expected, displaying the file if logged in. The issue is the same for all publishing settings (listed, unlisted, authenticated), and when logged in and out. I also tried with different types of files, and using vanity link, all to the same effect. Before doing any of this, I enabled the "Allow public file sharing" in "Site Settings".

It may be relevant that I am running the server behind a http reverse proxy, having set base path according to instructions in README. As far as I know, all other features work correctly.

![obraz](https://user-images.githubusercontent.com/25253395/233052859-fa9ceb68-b2be-45cb-a08c-385a85a3e1b7.png)

![obraz](https://user-images.githubusercontent.com/25253395/233053865-d916c51f-0e41-4fc9-aeca-a709ca899c3c.png)

![obraz](https://user-images.githubusercontent.com/25253395/233075321-553f0fed-55dd-405a-b4ed-b474beba52af.png)

Thanks in advance for any help!

**Comment by williamstein** [comment]
Is there any quick test you could do to make sure the problem is with the base path?  It might be way easier for us to fix this if you can come up with some steps to follow:

- do the following steps from a clean server and it works fine
- do the following steps from a clean setup but with a base path and it breaks

I know it's a lot of work, but we'd have to do the same.  It'll help a lot. Thanks!

**Comment by Maarrk** [comment]
No worries, thanks for suggestion on specific steps. I'll get back to you once I try them

**Comment by Maarrk** [comment]
I had the same issue on new containers, even not having a base path, and then another day something I did resolved it, also for my original instance. Since the problem behaved in the same way for different containers, it's probably on my host system.

I think I should close the issue, since I am unable to reproduce it, sorry to bother you.
