### ISSUE TITLE
nice to have in cocalc-v2: possibility to add the ChatGPT KEY on  project base.

### ISSUE THREAD

**Issue by arm2arm** [sagemathinc/cocalc-docker#186]
Hi, The ChatGPT integration is a nice addition to the projects. Unfortunately there is not way to track back the costs, to discover which project was causing the most costs.
Would be nice to add the OpenAI key in the project settings which is editable only by project owner.

**Comment by williamstein** [comment]
> Hi, The ChatGPT integration is a nice addition to the projects. Unfortunately there is not way to track back the costs, to discover which project was causing the most costs.

You *can* track which person causes the costs: see [the openai_chatgpt_log table](https://github.com/sagemathinc/cocalc/blob/master/src/packages/util/db-schema/openai.ts).

 Note that chatgpt usage happens entirely in the browser, and currently can't be initiated by a project.

**Comment by arm2arm** [comment]
thank you! this is enough for sharing/calculating the costs between the departments.

**Comment by williamstein** [comment]
Closing due to this being enough.
