### ISSUE TITLE
Project invite token

### ISSUE THREAD

**Issue by Anders-AAU** [sagemathinc/cocalc-docker#204]
When someone tries to join a project with any token, they get this error. I got the latest docker image for amd64 installed

TypeError: Cannot read properties of undefined (reading 'add_collaborators_to_projects')

**Comment by williamstein** [comment]
Thanks for the report.  This is fixed in cocalc (the upstream source), and will be fixed in the next cocalc-docker update, which I'm building right now:

<img width="1273" alt="image" src="https://github.com/sagemathinc/cocalc-docker/assets/1276278/c3ebe642-19f5-42f5-9189-faeed3a4a1a2">
