### ISSUE TITLE
cocalc-docker asking for payment when trying to use gpt4, cannot turn off

### ISSUE THREAD

**Issue by bombaglad** [sagemathinc/cocalc-docker#217]
I've set up cocalc-docker (from dockerhub) under Unraid, created an admin account and I am currently testing ChatGPT-integration. I've created an account with OpenAI, paid for API access and created a token, which I then pasted into the correct field in settings and enabled ChatGPT-UI.

When I'm for example editing a Latex document, choosing "GPT-3.5" works perfectly, it opens a chat window and outputs useful info. I am tracking the API usage through platform.openai.com and I can see it using "GPT-3.5 Turbo".

However, if I try to change the model I'm using via the GUI to "GPT-3.5-16k" or "GPT-4", CoCalc asks me for payment:
"You do not have enough credits to spend up to $0.64 since your balance is $0.00, and spending up to $0.64 would cause your balance to go below your allowed minimum balance of $0.00. Please add at least $2.50 to your account. There is a minimum payment of $2.50."

It seems I'm unable to add "money" to my balance or to allow negative balance. Is it possible to turn this feature off, disable the check or fake-add "money" to my own account?

Thanks in advance!

![Screenshot from 2024-01-22 18-09-49](https://github.com/sagemathinc/cocalc-docker/assets/44273538/662416a8-7cb7-4e74-964a-271c2da1d91f)

**Comment by williamstein** [comment]
> It seems I'm unable to add "money" to my balance or to allow negative balance. Is it possible to turn this feature off, disable the check or fake-add "money" to my own account?

It is possible to add money or allow a negative balance.    To add money, one way is to sign up for stripe, then put in stripe credentials for a test account and then you get to use any fake stripe testing card.  

Did you make a cocalc admin account? 

https://github.com/sagemathinc/cocalc-docker/blob/master/README.md#make-a-user-an-admin  

when you do that, you can set the min balance of any user in the admin page like this -- find the user (yourself), then click "Purchases", then click "Minimum Allowed Balance..." and set it to something very negative:

<img width="1434" alt="image" src="https://github.com/sagemathinc/cocalc-docker/assets/1276278/6b43c838-8647-4dca-a251-42c89d70b181">

I hope this helps. 

There's a lot of other things to do in case the above are not acceptable, ways to just directly edit the purchases table of the database to add money to your account, etc...

**Comment by bombaglad** [comment]
Thanks a ton, that worked! I already had made myself Admin, just didn't know that menu existed.

Though I think there should be a way to toggle that whole set of checks off, I didn't find anything on this topic in the documentation.

May I suggest adding this as a two-liner to the setup-guide for ChatGPT integration?
