### ISSUE TITLE
Other port than 443

### ISSUE THREAD

**Issue by Ra-Na** [sagemathinc/cocalc-docker#31]
Could you please add instructions how to use other ports than 443? I want to set up cocalc alongside an already running apache2 server.

**Comment by Crusher565** [comment]
This is supported. Just map a different port, when creating the docker instance, to 443.
The command should be the same except replace the 443:443 part with XXX:443 (the XXX is the port you wish to use). In case you have issues with your reverse proxy take a look at what I found out in: https://github.com/sagemathinc/cocalc-docker/issues/33
