### ISSUE TITLE
I am testing the recent docker image with datashaders/holoviews w/o success.

### ISSUE THREAD

**Issue by arm2arm** [sagemathinc/cocalc-docker#32]
Hello, 
Are there any chance to get running cocalc with a datashader/holoviews?
I am testing the recent docker image with datashaders/holoviews w/o success.

```python
import numpy as np
import pandas as pd
import holoviews as hv
from holoviews.plotting.bokeh.element import (line_properties, fill_properties,
                                              text_properties)
print("""
Line properties: %s\n
Fill properties: %s\n
Text properties: %s
""" % (line_properties, fill_properties, text_properties))

curve_opts = dict(line_width=10, line_color='indianred', line_dash='dotted', line_alpha=0.5)
point_opts = dict(fill_color='#00AA00', fill_alpha=0.5, line_width=1, line_color='black', size=5)
text_opts  = dict(text_align='center', text_baseline='middle', text_color='gray', text_font='Arial')
xs = np.linspace(0, np.pi*4, 100)
data = (xs, np.sin(xs))

(hv.Curve(data).options(**curve_opts) +
 hv.Points(data).options(**point_opts) +
 hv.Text(6, 0, 'Here is some text').options(**text_opts))

```

on the cocalc it produces: 
![holoview_demo](https://user-images.githubusercontent.com/2283443/47561095-a70fae80-d91a-11e8-98e0-e3f3037c1ec7.png)

The result should be something like this:
![holoview_demo](https://user-images.githubusercontent.com/2283443/47561027-6adc4e00-d91a-11e8-8e41-e9a13b95f474.png)

**Comment by ll-portes** [comment]
Did you try this?
```
from bokeh.plotting import output_notebook
from bokeh.resources import INLINE
output_notebook(resources=INLINE)
```

I'm having the same problem, but with the cocalc online. These commands above don't solve my problem online, but maybe could solve yours with the docker image.
