### ISSUE TITLE
X11 support on cocalc/docker

### ISSUE THREAD

**Issue by sboresch** [sagemathinc/cocalc-docker#37]
Based on the responses to my  [forum post with the same subject](https://groups.google.com/forum/#!topic/cocalc/ZQUVYc43HTg), here is the issue:

When having several users on a local cocalc/docker instance, only one ("the first") user can utilize the X11 support. X11 apps of all other users fail to open a display (xterm: Xt error: Can't open display: :9797250). The immediate reason clearly are the ownership/permissions of the X11 related  files/sockets in /tmp, e.g.,

drwxrwxrwt 2 44ce141d1409467cadc9b9d66acb38bb 44ce141d1409467cadc9b9d66acb38bb 4096 Jan  8 16:24 .X11-unix

As a further observation, the files/sockets owned by the "first user" get neither removed upon the user logging out, nor upon a restart of the container.

Thanks for looking into this

**Comment by west789** [comment]
How do you solve this problem? I meet the same issue. If you have solved it, can you share the solution. 
Thanks a lot!

**Comment by kmfrick** [comment]
First things first: are those files really the problem? `/tmp/.X11-unix` has mode 777 so another user should be able to overwrite it.

If they actually are the problem, I see two fixes/workarounds that might be possible:
1) Which files need to be deleted to make "following" users able to launch an X server and are they safe to delete on user logout? If so, deleting them (is `rm -r /tmp` and letting fs permissions take care of it too brutal? It probably is) on user logout using `~/.bash_logout` or `trap` would probably be a good workaround. 
2) Do those files *need* to be in `/tmp` or can we just set an environment variable and write them inside `~/.x11tmp` or something so they don't step on each other's toes?

**Comment by butsuri43** [comment]
Hi there, 

Changing access rights of the `/tmp/xpra/` folder inside the docker container to 777 has fixed the issue for me.

**Comment by williamstein** [comment]
> Hi there,
> 
> Changing access rights of the `/tmp/xpra/` folder inside the docker container to 777 has fixed the issue for me.

Thanks -- I'll seriously consider making this change to the official image somehow.  Any thoughts about when/how to do this in an automated way... ?

**Comment by AlxDfy** [comment]
`chmod -R 777 /tmp/xpra/`
^ This fixed it for me as well. Otherwise only the admin(?) or a project created by them could use any type of graphical application even xclock&

**Comment by williamstein** [comment]
Fixed this by making the tmp dir /tmp/xpra-{project-id}, which also maintains security (unlikely changing perms of /tmp/xpra).   Will be in the next cocalc-docker update, which should be this weekend...
