### ISSUE TITLE
CoCalc uses only one Core to compute

### ISSUE THREAD

**Issue by F-Forget** [sagemathinc/cocalc-docker#44]
Hi everyone 😄 

I’m not sure if that’s a bug or a feature, but I managed to run CoCalc on my own server that actually has an 8-Core Intel Core Xeon. What I’ve found is that a single ipynb won’t ever take more than a Core to compute, why is that? 

![image](https://user-images.githubusercontent.com/7460096/56044315-e422fe00-5d0c-11e9-951b-eda1c6fdad91.png)

My server has 8-Core but my calculations are bottlenecked because my notebook can only use one Core! I also saw that running 2 ipynb at the same time will use multiple cores. Is there a way to take advantage of it and use all cores for a single ipynb?

Thank you

**Comment by haraldschilly** [comment]
This is 100% a julia specific question. Here is a [query for multiprocessing](https://discourse.julialang.org/search?q=multiprocessing) to get you started with that topic :books:
