### ISSUE TITLE
project storage quota, user connect remote storage, send programs to remote container for processing

### ISSUE THREAD

**Issue by FastBlit** [sagemathinc/cocalc-docker#48]
Currently the docker container is vulnerable to being crashed by running arbitrary code and to being overfilled with large numbers of files. Implementing these 3 steps (increasing complexity) would resolve such common resource usage attacks.

**Comment by williamstein** [comment]
Much of this is out of scope for cocalc-docker.   We have a Kubernetes version of CoCalc that solves all these problems:  https://cocalc.com/pricing/onprem
