### ISSUE TITLE
Request for Docker for Windows support

### ISSUE THREAD

**Issue by njman** [sagemathinc/cocalc-docker#5]
Hi,

Installing Docker for Windows on Windows 10, then run:

    docker run --name=cocalc -d -v c:/cocalc:/projects -p 443:443 sagemathinc/cocalc

But page told "disconnecting...", with `docker logs cocalc -f`:

>   2017-08-27T00:36:10.617Z - debug: PostgreSQL.connect: "retry_until_success() -- err=command 'psql' (args=--user smc --host /projects/postgres/data/socket --port 5432 --list --tuples-only) exited with nonzero code 2 -- stderr='psql: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket \"/projects/postgres/data/socket/.s.PGSQL.5432\"?\n'"
> 2017-08-27T00:36:20.623Z - debug: PostgreSQL.connect: "retry_until_success() -- try 71"
> 2017-08-27T00:36:20.623Z - debug: PostgreSQL._do_connect: undefined
> 2017-08-27T00:36:20.623Z - debug: PostgreSQL._do_connect: "first make sure db exists"
> 2017-08-27T00:36:20.624Z - debug: PostgreSQL._ensure_database_exists: "ensure database 'smc' exists"
> 2017-08-27T00:36:20.624Z - debug: PostgreSQL._ensure_database_exists: "psql --user smc --host /projects/postgres/data/socket --port 5432 --list --tuples-only"
> 2017-08-27T00:36:20.631Z - debug: PostgreSQL._do_connect: "Failed to connect to database -- command 'psql' (args=--user smc --host /projects/postgres/data/socket --port 5432 --list --tuples-only) exited with nonzero code 2 -- stderr='psql: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket \"/projects/postgres/data/socket/.s.PGSQL.5432\"?\n'"
> Failed to connect to database -- command 'psql' (args=--user smc --host /projects/postgres/data/socket --port 5432 --list --tuples-only) exited with nonzero code 2 -- stderr='psql: could not connect to server: No such file or directory
>         Is the server running locally and accepting
>         connections on Unix domain socket "/projects/postgres/data/socket/.s.PGSQL.5432"?
> 

So, really support docker for Windows on Windows 10?
'

**Comment by wrenoud** [comment]
An alternate approach that I had success with was to make a docker volume and use that for storage.

```
docker volume create cocalc-volume
docker run --name=cocalc -d -v cocalc-volume:/projects -p 443:443 sagemathinc/cocalc
```

I'm not sure how easy it is though then to backup files.

**Comment by vwxyzjn** [comment]
@wrenoud That works. Thank you!
