### ISSUE TITLE
coffee hangs on `require 'c'`

### ISSUE THREAD

**Issue by DrSAR** [sagemathinc/cocalc-docker#50]
When trying to reset a users password, `coffee` hangs on `require 'c'`:
```
root@f98a06bd5f36:/# coffee
coffee> require 'c'
```
This is on an updated docker installation in a ubuntu host system. How can I debug this more?

**Comment by haraldschilly** [comment]
hmm, I suspect it isn't able to connect to the database. does it run and everything else works? this should print a few lines of debug output, and then press return at least once to get a new clean prompt.

**Comment by DrSAR** [comment]
the rest of the system seems to work. through random rebooting of the docker, the host, killing of some jobs mentioning coffee etc I was suddenly able to get it to talk to me yesterday night -- not sure what did it in the end. However, now that I'm trying it again, I get the same silent treatment as soon as I `require 's'`. There is no debug output -- just as I quoted above and then silence. The process `node /usr/bin/coffee /cocalc/src/smc-project/local_hub.coffee` runs at 100% CPU but there is no more I can make out.

**Comment by rsargent** [comment]
This happens to me too, cocalc-docker running in Ubuntu 18.04

**Comment by DrXyzzy** [comment]
Is there any output after you type `require 'c'`? As @haraldschilly notes above, there is debug output that normally comes after `require 'c'` and obscures the prompt. It can take several seconds to appear the first time. After the output, the coffee interpreter is still running and ready for you to type a command, e.g. you should be able to get a new prompt by hitting Enter.

**Comment by DrSAR** [comment]
No output. That's why I copied my interaction above. That's the last interaction you will get in that shell. Pressing Enter gets swallowed (neither a new prompt nor a simple line advance). It sits and broods. Ctrl-C won't work either. I haven't had the patience to wait it out but at a minimum it hangs for 10min, in all likelihood for ever, though.

**Comment by DrXyzzy** [comment]
William has implemented a new Admin password reset functionality. It's documented here:
https://github.com/sagemathinc/cocalc-docker#reset-a-users-password

There's no longer any need for `require 'c'`, and you'll see it is not mentioned in the latest cocalc-docker README.md.

Of course, you have to upgrade your cocalc-docker install as explained here: https://github.com/sagemathinc/cocalc-docker#upgrade

Thanks all, for reporting the issue.
