### ISSUE TITLE
Adding Haskell kernel ?

### ISSUE THREAD

**Issue by delanoe** [sagemathinc/cocalc-docker#62]
Hello,
do you have an image with the Haskell kernel ?

If not which steps/documentation I could follow to add it ?

Many thanks for your help and this support of this amazing project.

**Comment by ktaletsk** [comment]
You can build your container on top of this container and install whatever you want (see https://github.com/ktaletsk/CuCalc/blob/master/Dockerfile for example). Replace everything after `FROM: sagemathinc/cocalc` with commands from here: https://github.com/gibiansky/IHaskell#installation and it should add it

**Comment by delanoe** [comment]
Great! Many thanks for your quick answer, I will try that way.

**Comment by TTEUz** [comment]
@ktaletsk hi, i'm student of computer science here in Brazil (Manaus, AM) in UFAM college; i'm trying to setup a CoCalc server with haskell kernel but somehow i didn't have succeed. Can u please explain in some kind of "tutorial for dummies"
