### ISSUE TITLE
Cocalc Docker Jupyter cant use scipy even tho it is installed and usable in a test terminal

### ISSUE THREAD

**Issue by Meistermagier** [sagemathinc/cocalc-docker#63]
import scipy

results in
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-4363d2be0702> in <module>()
----> 1 import scipy

ModuleNotFoundError: No module named 'scipy'

I checked using the Terminal if scipy is installed and it is

**Comment by williamstein** [comment]
scipy works fine now in jupyter with both the systemwide and sage python3 kernels.
