### ISSUE TITLE
Instability issues with latest image

### ISSUE THREAD

**Issue by doppioandante** [sagemathinc/cocalc-docker#67]
Hi, I run cocalc inside my own vps using this docker image. A few days ago I updated the image with to the latest version but unfortunately cocalc is now pretty shaky. Sometimes while I'm using it will hang. Actually, I think that it hangs only when it is suspended but I'm not sure about that, it might be unrelated.
When this happens I have to restart the docker image manually; today I tried to log into it to look around but a simple `docker exec -it cocalc bash` will give the following message
```
unable to find user root: no matching entries in passwd file
```
From a quick search on this error message nothing turned out, so I'm posting the issue here in case anybody has had this behaviour from cocalc.
Is there any tip to debug it?

P.S. thanks for the amazing work and for this docker image

EDIT: I'm running on ubuntu server 19.04

**Comment by williamstein** [comment]
> unable to find user root: no matching entries in passwd file

I've definitely never seen that.  It seems like your /etc/passwd file got corrupted somehow.  I have no clue how that is possible, since cocalc doesn't directly edit that file.

**Comment by williamstein** [comment]
> unfortunately cocalc is now pretty shaky. Sometimes while I'm using it will hang.

It would be very helpful if you could be a lot more precise...

**Comment by doppioandante** [comment]
Hi, I have restarted the server a few days ago and since then I got no trouble. I think that it was probably rocker being at fault here and not cocalc. Sorry for the trouble, if I experience the issue again I'll reopen.
