### ISSUE TITLE
favicon is broken

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc-docker#72]
Probably broken by new landing page code:

![image](https://user-images.githubusercontent.com/1276278/77929873-046e0480-725f-11ea-9ddc-762a48b471ff.png)

@haraldschilly how to fix this?

**Comment by haraldschilly** [comment]
Hmm, I'm not sure what's going on. Was the page fully loaded? Anything suspicious in the network console, where it shows the requests?

For me, that's what I get for the new main index page:

![Screenshot from 2020-03-30 17-44-53](https://user-images.githubusercontent.com/207405/77933227-dadcc980-72ae-11ea-81f3-45e2dc9a185f.png)

and here the `/app` page

![Screenshot from 2020-03-30 17-49-06](https://user-images.githubusercontent.com/207405/77933251-e29c6e00-72ae-11ea-819d-dbf3cb1cbbe0.png)


In both cases it's `<link rel="icon" type="image/png" href="/webapp/favicon-32x32.png" sizes="32x32">` and I do get some icon as a reply.

**Comment by williamstein** [comment]
Do you **see** a favicon when you visit https://kucalc.sagemath.org:4043/ ?

**Comment by williamstein** [comment]
Maybe you customized the favicon there as admin or something?

**Comment by williamstein** [comment]
Seems to be working now...
