### ISSUE TITLE
cocalc : add a julia kernel to jupyter

### ISSUE THREAD

**Issue by leakim-tsp** [sagemathinc/cocalc-docker#74]
I have installed cocalc image on google cloud.
I have tried to add julia 1.4 kernel to jupyter but it failed.
I have set .julia to be here : /usr/local/share/.julia.

**Config**

_julia bin directory : /opt/julia/bin/julia_

    

> ln -s /opt/julia/bin/julia /usr/local/bin

_IJulia is installed_

using Pkg ;
Pkg.add("IJulia");

_etc/julia/startup.jl_

ENV["JULIA_DEPOT_PATH"] = "/usr/local/share/.julia" ; 
ENV["JUPYTER"] = "/usr/local/bin/jupyter"; 

_/usr/local/share/jupyter/kernels/julia-1.4/kernel.json_

```
{
  "display_name": "Julia 1.4.0",
  "argv": [
    "/opt/julia/bin/julia",
    "-i",
    "--startup-file=yes",
    "--color=yes",
    "--project=@.",
    "/usr/local/share/.julia/packages/IJulia/yLI42/src/kernel.jl",
    "{connection_file}"
  ],
  "language": "julia",
  "env": {},
  "interrupt_mode": "signal"
}
```

**Error I get**

```
sh-4.4$ jupyter console --kernel=julia-1.4
ERROR: LoadError: ArgumentError: Package IJulia not found in current path:
- Run `import Pkg; Pkg.add("IJulia")` to install the IJulia package.

Stacktrace:
[1] require(::Module, ::Symbol) at ./loading.jl:892
[2] include(::Module, ::String) at ./Base.jl:377
[3] exec_options(::Base.JLOptions) at ./client.jl:288
[4] _start() at ./client.jl:484

```
It seems that I don't understand Julia package management for projects (""--project=@." options in kernel.json).

Thanks in advance for your help.

**Comment by williamstein** [comment]
NOTE: also posted at https://stackoverflow.com/questions/61037701/cocalc-how-to-add-a-julia-kernel

**Comment by williamstein** [comment]
A Julia dev remarks:

> https://github.com/xiaodaigh/julia-data-science-base-docker-img   
> Add some magic from here would help.

**Comment by williamstein** [comment]
I'm releasing a new cocalc-docker in a few minutes that includes an updated Julia and a working kernel.
