### ISSUE TITLE
add python3 kernel

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc-docker#8]
See https://github.com/sagemathinc/cocalc/issues/2149

**Comment by lwintermelon** [comment]
Besides Python3 kernel, what about other kernel, like octave

**Comment by lwintermelon** [comment]
Besides Python3 kernel, what about other kernel, like octave

**Comment by haraldschilly** [comment]
Octave is not installed, hence the kernel wouldn't help much. You can easily modify the Dockerfile and add octave for your own purposes, though...

**Comment by lwintermelon** [comment]
Thanks for your quick reply. 
Jupyter  Notebook on https://cocalc.com is as below.
![image](https://user-images.githubusercontent.com/18533670/30776612-4812d866-a0dc-11e7-90ba-9c0212dd5a2e.png)
So how to run octave(or others) in Jupyter  Notebook or Sage Worksheets on local machine, by modifying the Dockerfile to install octave, octave_kernel and configure it(how?) ? What about others,is it documented ?

**Comment by lwintermelon** [comment]
Try to add octave kernel,see https://github.com/lwintermelon/cocalc-docker/commit/4d16d145ee2e334c5e575fcdc61ec4d76a42eb36 
It is strange that it didn't work if I run the commands added in Dockerfile in a container from sagemathinc/cocalc even  if add read permissions to  `/usr/local/share/jupyter/kernels/*` for all users, and it seems that all kernels turned to doesn't work. I'm totally a newbie, don't know why.sorry for my bad English. will test it after building a new image.

**Comment by vwxyzjn** [comment]
I tried to install the kernel by hand, but it would not work. I have no idea how cocalc get the kernel list...

**Comment by vwxyzjn** [comment]
@ktaletsk thanks! It works as long as you 

1. Put the following code in the ``Dockerfile`` and run ``docker build``

```Dockerfile
#Add Conda kernel to Jupyter
RUN source activate sympy && \
    python -m ipykernel install --prefix=/usr/local/ --name "python3"&& \
    source deactivate 
```

2. Or use the **Terminal** of your project, **not the docker shell** to execute the following code

```
export PATH=/opt/conda/bin${PATH:+:${PATH}} 
source activate sympy
(sympy) ~$ python -m ipykernel install --user --name sympy --display-name "Python 3.6 (SymPy)"
```

Here is the peculiarity: if you build the image first and then run the code 

```Dockerfile
#Add Conda kernel to Jupyter
RUN source activate sympy && \
    python -m ipykernel install --prefix=/usr/local/ --name "python3"&& \
    source deactivate 
```

the ``python3`` environment will not appear in the cocalc kernel list. Any idea why?

Thank you for your help.

**Comment by williamstein** [comment]
Now done.
