### ISSUE TITLE
nodejs is not the recent one in Dockerfile-light .

### ISSUE THREAD

**Issue by arm2arm** [sagemathinc/cocalc-docker#82]
Just noticed that the node is not the 10-th version it is still pointing to 8.x in the [Dockerfile-light](https://github.com/sagemathinc/cocalc-docker/blob/5e82d49229a211204001846b176f6681c3c37df9/Dockerfile-light#L135) file

**Comment by williamstein** [comment]
Interestingly, I was planning on deleting Dockerfile-light today since it wasn't being maintained and I didn't know anybody used it.

**Comment by williamstein** [comment]
OK, I'm deleting this now, which will close this issue.  Perhaps better would be some sort of build arg that prevents building SageMath and installing as many packages, or dividing the build into two stages.
