### ISSUE TITLE
Error installing Cocalc Docker under Win 10 pro

### ISSUE THREAD

**Issue by ingodahn** [sagemathinc/cocalc-docker#83]
The following error occurs after creating cocalc-volume (in powershell as well as with cmd):
C:\Users\User>docker run --name=cocalc -d -v cocalc-volume:/projects -p 443:443 sagemathinc/cocalc
Unable to find image 'sagemathinc/cocalc:latest' locally
docker: Error response from daemon: manifest for sagemathinc/cocalc:latest not found: manifest unknown: manifest unknown

**Comment by williamstein** [comment]
Please try again.  I made a mistake with the image I uploaded recently, so deleted it from dockerhub.  You probably have a partial broken pull of the image. 

I regularly test cocalc-docker on Windows 10 pro myself, by the way since my main work laptop is a Windows 10 pro laptop.
