### ISSUE TITLE
upgrade to a newer (than 18.04) version of Ubuntu for the base image; in particular, switch to "python" being python3 by default!

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc-docker#90]

**Comment by williamstein** [comment]
done, now at 20.04

**Comment by Alessandro-Barbieri** [comment]
What about using the node version shipped with the distro?

**Comment by williamstein** [comment]
> What about using the node version shipped with the distro?

Sure, please feel free to create a ticket about doing that.   Note however, that we maintain cocalc in a bunch of environments (not just cocalc-docker), and possibly having to support multiple node versions at once could complicate that too much.
