### ISSUE TITLE
Cannot upload larger files

### ISSUE THREAD

**Issue by StiaanGerber** [sagemathinc/cocalc-docker#92]
I cannot seem to upload a file larger than approximately 20MB. I've monitored the network traffic and found that the transfer seems to stop after precisely 100 seconds. At this point the file upload in cocalc seems to hang/freeze. No errors in browser console or in /var/log/nginx/error.log.

Smaller file uploads work without a problem.

I'm running behind nginx reverse proxy (as described in "Installing behind an Nginx Reverse Proxy")

I've tried to change the nginx config, but no luck.

Any idea why this is happening?

**Comment by williamstein** [comment]
There isn't a 20MB file upload limit:

![image](https://user-images.githubusercontent.com/1276278/87461372-319eb280-c5c3-11ea-9180-e9c4263c4db4.png)

However, uploads are broken into chunks and uploaded, and there are time limits on the size of each chunk.  See the source code here:

https://github.com/sagemathinc/cocalc/blob/1a7d24bc580998260c64fa675caddca5108e1d9c/src/smc-webapp/file-upload.tsx

There's a big comment there about how the parameters were chosen, and your internet is sufficiently slow that it breaks those assumptions, e.g., 

> "If a user can do 1MB/s, then they can upload 100MB in 100 seconds, hence 32MB in 100 seconds seems a reasonable assumption....  If it really takes over a minute to upload 32MB, then the user isn't going to upload a very big file anyways, given TIMEOUT_M."

This was all designed to deal with proxying through cloudflare... 

I'm not opposed to changing the parameters in file-upload.tsx to better match the real world (or make them configurable somehow via the Admin configuration page).  In any case, does this look like your issue?   What exactly is your upload bandwidth, as reported by cloudflare?

**Comment by StiaanGerber** [comment]
Thanks. Yes, I think this is the issue. My upload speed is only 2 Mbps (lowercase b for bits). I'm in South Africa, where that is not uncommon, but we definitely need to upload much larger files, even if it takes forever.

Is there a quick way for me to patch this in the docker container? I estimate that if I can set CHUNK_SIZE_MB = 8, it should be ok.

**Comment by williamstein** [comment]
I've changed the CHUNK_SIZE_MB to 8 in the official cocalc master sources.  There will be [a new version at Dockerhub](https://hub.docker.com/r/sagemathinc/cocalc/tags) sometime today, so you can [upgrade to it](https://github.com/sagemathinc/cocalc-docker/blob/master/README.md) and try it out.

**Comment by StiaanGerber** [comment]
Great. I've tried it and can confirm that large file uploads now work without a problem.

 Thanks for the quick fix!

**Comment by williamstein** [comment]
Excellent, and thanks for the report!

**Comment by niklas-2** [comment]
For most of the files I have tried to upload I get the error 413 Request Entity Too Large. Any idea why this is happening? With the current container version it seems to happen more frequently.
