### ISSUE TITLE
X11 copy buffers in docker image are not shared between X11 and web browser

### ISSUE THREAD

**Issue by arm2arm** [sagemathinc/cocalc-docker#93]
X11 copy buffers in docker image are not shared between X11 and web browser
to reproduce:
* start docker
```
docker run --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all  --name=mysimple -d -v /projects:/projects -p 443:443  sagemathinc/cocalc
````
* login and create a project on chrome under windows 10  
* create x11 application
* start writer or firefox
* copy in X11 window text inside the firefox
* paste it in OS does not appear
* the copy buffer inside the cocalc terminal containing data from Firefox: ```xclip -o -selection primary```

then buffers are separated between **OS** and **xpra**

on the **cocalc.com** everything is working as expected.

Observations:
* xpra on the docker image is differ as cocalc.com
* reinstall on the docker same version does not fix the problem

**Comment by williamstein** [comment]
I've made this ticket over on the cocalc side, since just getting everything to version 4.x is the way to go:  https://github.com/sagemathinc/cocalc/issues/4745

**Comment by haraldschilly** [comment]
Version 3 has long term support until 2023, while version 4 (I guess 4.0) is only supported until Q3 2020. My feeling is it's better to stick with the more stable version to avoid incompatibility problems from happening. Of course, later in e.g. Q1 2021 we can revisit this.

**Comment by williamstein** [comment]
>  My feeling is it's better to stick with the more stable version to avoid incompatibility problems from happening.

Cool -- maybe you already have code to install xpra 3.x into cocalc-docker, instead of xpra-4.x (the default)?

**Comment by haraldschilly** [comment]
Well, just change this to `apt-get install -yq 'xpra=3.*'` … if copy/paste works then, we do know it's caused by version 4.

**Comment by williamstein** [comment]
Downgrading xpra did NOT work.  So it must be some other problem.  Will require looking at the source code...

**Comment by williamstein** [comment]
the real problem is we use the `xsel` command for copy.. and that isn't installed at all in cocalc-docker!

**Comment by haraldschilly** [comment]
oh, I see, I should then better make sure it is installed in production as well.
