### ISSUE TITLE
install pythontex into the docker image

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc-docker#96]
Nobody has requested this, but it seems like a good idea for completeness and compatibility.

That said, I searched around for about 15 minutes... and have **absolutely no clue** how to install Pythontex.  It's surreal how badly documented the install process is (or I'm just not seeing it).  The top hit is this from 2013:

https://tex.stackexchange.com/questions/151478/installation-of-pythontex

which doesn't even have an answer.

**Comment by haraldschilly** [comment]
You can use dpkg to search for binaries, e.g. `dpkg -S pythontex` tells you it's `texlive-extra-utils`

one cocalc specific thing is that we use `pythontex3` for python 3. For Ubuntu 20.04, it changed to just `pythontex`. So, what I did is to add a symlink `/usr/bin/pythontex3 -> /usr/bin/pythontex` .

Regarding your link, the [first answer](https://tex.stackexchange.com/a/151531/11611) looks correct to me. Ubuntu just packages this up for us.

**Comment by williamstein** [comment]
We do this now.
