### ISSUE TITLE
use nodejs version from ubuntu

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [sagemathinc/cocalc-docker#98]
I see that docker runs a different nodejs version from the one currently shipped by ubuntu (and debian)
```
# Install Node.js and LATEST version of npm
RUN \
     wget -qO- https://deb.nodesource.com/setup_12.x | bash - \
  && apt-get install -y nodejs libxml2-dev libxslt-dev \
  && /usr/bin/npm install -g npm
 ```
Since I'm trying to unbundle all the programs (to run it outside docker) I would like to have packages installed from the distribution repository (I have tried but different versions of nodejs can cause undetected problems here).

**Comment by williamstein** [comment]
Currently CoCalc's source code only supports node version 14, and CoCalc will _definitely not fully work_ with node version 12, which is what's in Ubuntu 20.04.      The backend uses a lot of functionality from node.js's filesystem API, etc., which has improved a lot from node 12 to node 14.
